name: python

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: pip install -r example/requirements.txt
      - run: pylint .
