name: Run Python checks such as linting and testing

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - run: pip install -e .
      - run: pip install -r dev-requirements.txt
      - run: pip install -r examples/http-api/requirements.txt
      - run: pip install -r examples/citrineos/requirements.txt
      - run: pip install -r examples/citrineos/simulator/requirements.txt
      - run: pylint optivgi
      - run: pylint --init-hook="import sys; sys.path.insert(0, 'examples/http-api/src')" examples/http-api
      - run: pylint --init-hook="import sys; sys.path.insert(0, 'examples/citrineos/src')" examples/citrineos
